---
# Source: logging-operator-logging/templates/logging.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-operator-logging
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  fluentbit:
    annotations:
      fluent-setup/enable: "true"
    image:
      pullPolicy: Always
      repository: fluent/fluent-bit
      tag: latest-debug
    logLevel: debug
  clusterDomain: cluster.local
  controlNamespace: default
