---
# Source: logging-operator-logging/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: logging-operator-logging-fluentd-tls
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRYUhKSTdqa2ljWWI0ZkN6RGE3d29uekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl6TURjeU1EQXlNVFkwTTFvWERUTXpNRGN4TnpBeQpNVFkwTTFvd0ZURVRNQkVHQTFVRUF4TUtjM1pqTFdOaGRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBUHBOeEFFbkpRZGtzZ2hZVjJIRDNxcHpnOGhpRmhxZ2trWm5FenJFWU9sVWRpQ2QKN0ltQmVCN1Qzc0p4a1BuUWxZRGUxWllyOVBJY2RDd1A2dnJjeElCMTN6TXM3eXkzNWRpTTZ2OVN0ZTVLRDFVRgptbUpMMkV5TUVEK2RDVWtLOWlGRGRlVCtIcUpnNnZERXpjdHA1MVI5MGx6UkNtSmE2dXBkL1h5cmNUN2VKRENiCjVvZTJ5T0tWdnhNSkVLaXREL0FRYkZhcnhJRGRFTkc2WHI2Wms3dXdWaWx0VTZFbmlLbE56eWFlb2pXS3NXOTAKVC9SZ1YzU3JZZU5DdldMdHBxcWxvYjFEY0p1TEIrUXc4UzlnUHRsVGtHYy9IQkRKQzFEQzVVd3hTSEFxcE0wLwpkQ2JOVFNvRzF2cEZsVXRSUUZjbXFBU3NTaDJpSXh4RnFFTTRGTjhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlExMVFBNjVKL0w3dTNyUngxcmdZcWV4dHU4VGpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFBYlpTWFNXRjB6YWlsOU50bGZ4T3A3OVB4WlhuQXpyZXRmZG5SUXZ5azBwbVlIcm5aTkltClpUUndVY2R4WUFmWXdQUzhUUk9YZmZGdWpqRmYvdHp1clhzU3Rvc2o2di9McWkwNTlweFc0d2FSU24wbW92bGUKc3VrNTloQm5zWTMrZk1YS3NIc3ZpY2pEL1p0ZnNzWnJUM0p1dllTdkFkU2hINDVSN2VSNUE0Qm9rV1VMSUlzegpsNVBta3MvZmxHZ0FWUHhYQjBsUElvVzNjNHRhV3JMdlphQzFHV2JrOUFhY3p4KytjbklUT25hWm4rNGdsVmk3Cm5TU0x2R0M5Ym8rMTIvQ0VJcTV0Q3A2YU9BK1pzY2NId2NOamQ4QmdLQkFPM1F6ekNuTTNyOHROWUt2K2lPTXAKNC9ET3FrTHl2NkhzaTAyems5WkY2VFY1ZnVuUUIvb2ZRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lSQUlHaG1UR3ZZR3pTZDhCR0ljUTJvVlF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2MzWmpMV05oZEMxallUQWVGdzB5TXpBM01qQXdNakUyTkROYUZ3MHlOREEzTVRrdwpNakUyTkROYU1FVXhRekJCQmdOVkJBTVRPbXh2WjJkcGJtY3RiM0JsY21GMGIzSXRiRzluWjJsdVp5MW1iSFZsCmJuUmtMbVJsWm1GMWJIUXVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQzM1L2JYVVQvS21KN09jbHM1YTJqTjdvUndtb2Y4N0hTdUZUWHYyd2RQS0ZoRQpLNjBDUzRJOG9XRHFLTzZucm1VQVk2MVBJNjNPMjQvMWtndlMxOEpJODlKcXJWMnA5UGw5dno5QlBDbW05aTE3CjlXTkVGZXFSMlNzWkF2a1A5a2k2TWg2TC9aSjRJUHNCUXhTZ1h6aGJwd3BPd0d5TDU2elFnMkdMYnRpcGlibysKR1dJU1o0Uk1UQzdQOXNsNitFOEdJZzAvQW9neUxrOFEzTURrMU1LK2Ezdk5IZmhGd1M4WndsSTRIeDRrUnRPMgpxdytCbEVaZngyKzJMN2JReE10VXJaUHVEa3ZTYm1uMDNha3lZc21tdUNwODlueW5TWk1talRJUU1QRWsxZ3FlCnhnc3BSWDNTd09Dck1pU1NBYS9jUG5wNVRCZHBQMkVVU2RWSGtTWE5BZ01CQUFHallEQmVNQTRHQTFVZER3RUIKL3dRRUF3SUZvREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFILwpCQUl3QURBZkJnTlZIU01FR0RBV2dCUTExUUE2NUovTDd1M3JSeDFyZ1lxZXh0dThUakFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQXpmanJsM3JxZTQ2UVVCWTdWS2hkMDVTNDlLZENKV2VObUhubHc5N21EbXdCaHpWelpoMXAKV0dCSTQyUllmQnNqTnhYZ2hVVU1jYXRoalJ2Vm5LejlwTENHL1JuQXhiQmFvK0VpWFlPcHZpbTRPS2d2QnpYRwpBVEt5UlI4RmJmT0RWbTFKRDQrenAxWUgvYURSME9mc0lZcEZQcTA1SkJHc2FKK08zYkRQbkkxOFo4NHJQaks4CjM3eVg3eEd2VnhYMDU3UVlGSXdnQ1RmdkdhZEdoVmozRk9kVjg0VU5NWjdpbkZ3aGlTSlRYOHRKajhsazB3emEKdlFVS0ZCQThWS2k3dGtZd2J2ODZVcUE1Wk9VVStwK3IyUGRVVkJSTGoxdE85R3BrMElCbVlNdHBNdGZqWXdRRwprOWdsYzdtbFlIWVVGdVVNaGhQM2ZFT2taTFRjNVRpQ1d3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdCtmMjExRS95cGllem5KYk9XdG96ZTZFY0pxSC9PeDByaFUxNzlzSFR5aFlSQ3V0CkFrdUNQS0ZnNmlqdXA2NWxBR090VHlPdHp0dVA5WklMMHRmQ1NQUFNhcTFkcWZUNWZiOC9RVHdwcHZZdGUvVmoKUkJYcWtka3JHUUw1RC9aSXVqSWVpLzJTZUNEN0FVTVVvRjg0VzZjS1RzQnNpK2VzMElOaGkyN1lxWW02UGhsaQpFbWVFVEV3dXovYkpldmhQQmlJTlB3S0lNaTVQRU56QTVOVEN2bXQ3elIzNFJjRXZHY0pTT0I4ZUpFYlR0cXNQCmdaUkdYOGR2dGkrMjBNVExWSzJUN2c1TDBtNXA5TjJwTW1MSnByZ3FmUFo4cDBtVEpvMHlFRER4Sk5ZS25zWUwKS1VWOTBzRGdxeklra2dHdjNENTZlVXdYYVQ5aEZFblZSNUVselFJREFRQUJBb0lCQUFxNDVvWmxRVS9obUJpMwpTQ1JQNDl0bDFhanZDWkN3aEprRnVaQlRkOWlncEl6TTh4aFlLSzY2UmZsQkM3RVJGT2h4NTAvZTU2cFEyTkxiCmdmNzMvMmJiZUdBcDNYVWtTRXVSay9HTXZXenptM0ZIdkZMaTZEczZxeTJaSThaUGVLd0tjZ2Q5Y0VXNnZvZXoKVG9lUEphMEtUeXFLUTRuZ3B3MjlLem5DNjdUdXJuVFpvYU5DK0E4TDk0SGJlYjdjaEdhQy91SXZwQnZtajE1SwplbjEvbHJrNlRTVUk5bWFLOUhnY2JYWEhjNDlMMXFIMlhrT002S3VOaHkrVzFCYmJxaHkyVmdhdlJ0dXpQak0vCndreENqSjIwbytZdG5oa1dmVk5aVHpibkpsdm84aTB4K3U5NXY1dE45Vkh1VEpvRnZFTVJCcGJ2cy9GT3B4dGMKa3JKMG1RMENnWUVBMTY0VDNDY0x2amlNanNlUDZHMDQ3RVp4a0hRQThQVEN2YzRkblFyNnNMZ1ZReHNyZDNnTgpYendyQkRSWmQ1RVlBY3ZFb0M2YkpTQWlmR1VEUmFVclFtNGpZeGdKNzBPTlZNZy9VekYxSnZMUndOZ3k0UkVCCkJueWJpaGRzc2VBTXhHSlZzZC9SbTFuUThmQnErSWVOSWxQYjQyeGZoR0Y3UXhmRTBDVjk0K2NDZ1lFQTJrbEQKLys0aHUxczczcDd5cWZWbzM2R2x6dXVxaWxjSklReDlCd3NYRjBOTnNCQTAzb0FIRndOaWlmYlk3R2RvQ290YwpWaU5rbElXQ21SQU02RkJsOHJ0L09IanZzSk5MV1RZaWpiNnRaSUxvUDRPUXZOWit5bEFmdHBBb2RYZFpjdGp2Cm92UlJ0Y2YxREs5cDhTQytPMWJhckg0UWZsUEU1TE8yeTdhNWNpc0NnWUVBekxBcnJ2THJoU0w3Mm9Gd2hRQXIKVnFsZ0c5ek1DK0h1Yzk0S1lzRkp1NjlvbG1CUnR6Y2JVYmV6aDNEN082dGE0bEYxa1NQS0g4aklrYy8zOC8vVgo5MXk1ZnRFUWxKOUNvU1RPWEhFQ291MHR2ZHd4SlVKUys4b0VmMkROeWw0OUg1L0hmbUZROXlPZFZnOTZKZFhYClRxM1JjSnVvWnVWdzZ2TEMyVnZMaHg4Q2dZRUEwRXBwSUtYU2VqMHNlOW1nSkoyUVhSU2FhMEJsazJ4SndjZHcKNW0rbXNRUC85YWtCU2U5UTFKemVRbGZSMW9NMXZCb1BHZ0xienYwM0NXZFBhYjZPQ1hqd2hLcWh6UlJBS2ZpRwpNRXRxbVNaeEIybzdpbllDdG5xT1NGNTJ2T0FOOHBFZTJaZlpBR1MxYUUxYUFrVUVRUXMzenJEY2ZDN2pDbmlTClRRRW5JOUVDZ1lCbEdsNyt2bDBYd2lSMENJNTQyakxlZk41c1NRRksvOFk4QjVnMTFzdnpFT24yY3JBaWdGNkwKYkhqcmx4dkVTOGcyQlV4Vm5Xc0xpdEkva2RDN3BaV0pXUU9QRjNvNW85S0hRYUtEcW96ZGlJbVc1b1gvTnpxSQp2NVgyMS9sSzJJaEhKMkZkV3Bra2dMUWdRRHVIRVd1WFRQanhPOVFRaEFkbnZybVBQQUpENlE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: logging-operator-logging/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: logging-operator-logging-fluentbit-tls
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRYUhKSTdqa2ljWWI0ZkN6RGE3d29uekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl6TURjeU1EQXlNVFkwTTFvWERUTXpNRGN4TnpBeQpNVFkwTTFvd0ZURVRNQkVHQTFVRUF4TUtjM1pqTFdOaGRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBUHBOeEFFbkpRZGtzZ2hZVjJIRDNxcHpnOGhpRmhxZ2trWm5FenJFWU9sVWRpQ2QKN0ltQmVCN1Qzc0p4a1BuUWxZRGUxWllyOVBJY2RDd1A2dnJjeElCMTN6TXM3eXkzNWRpTTZ2OVN0ZTVLRDFVRgptbUpMMkV5TUVEK2RDVWtLOWlGRGRlVCtIcUpnNnZERXpjdHA1MVI5MGx6UkNtSmE2dXBkL1h5cmNUN2VKRENiCjVvZTJ5T0tWdnhNSkVLaXREL0FRYkZhcnhJRGRFTkc2WHI2Wms3dXdWaWx0VTZFbmlLbE56eWFlb2pXS3NXOTAKVC9SZ1YzU3JZZU5DdldMdHBxcWxvYjFEY0p1TEIrUXc4UzlnUHRsVGtHYy9IQkRKQzFEQzVVd3hTSEFxcE0wLwpkQ2JOVFNvRzF2cEZsVXRSUUZjbXFBU3NTaDJpSXh4RnFFTTRGTjhDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlExMVFBNjVKL0w3dTNyUngxcmdZcWV4dHU4VGpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFBYlpTWFNXRjB6YWlsOU50bGZ4T3A3OVB4WlhuQXpyZXRmZG5SUXZ5azBwbVlIcm5aTkltClpUUndVY2R4WUFmWXdQUzhUUk9YZmZGdWpqRmYvdHp1clhzU3Rvc2o2di9McWkwNTlweFc0d2FSU24wbW92bGUKc3VrNTloQm5zWTMrZk1YS3NIc3ZpY2pEL1p0ZnNzWnJUM0p1dllTdkFkU2hINDVSN2VSNUE0Qm9rV1VMSUlzegpsNVBta3MvZmxHZ0FWUHhYQjBsUElvVzNjNHRhV3JMdlphQzFHV2JrOUFhY3p4KytjbklUT25hWm4rNGdsVmk3Cm5TU0x2R0M5Ym8rMTIvQ0VJcTV0Q3A2YU9BK1pzY2NId2NOamQ4QmdLQkFPM1F6ekNuTTNyOHROWUt2K2lPTXAKNC9ET3FrTHl2NkhzaTAyems5WkY2VFY1ZnVuUUIvb2ZRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvekNDQWVlZ0F3SUJBZ0lRTUx1dUNXbUZERVY0Y3liTXY1VWxvekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl6TURjeU1EQXlNVFkwTkZvWERUSTBNRGN4T1RBeQpNVFkwTkZvd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1ERUQ0NWE0eFhoCjVJU0srMUJVUzkwemsyR05oVEJSTGNoZUUxRWdQOWFVdC93dGhPWnBXaDM2NW9MWThYY2p1NzRFNzdQZi9JdjAKc2dQM3RlYjJhZlQxa0VvQkV6Z3pFL0xuVzd2REpyTWxXTWJBMGJ6Ykhid1gweE9oaWxlSDhGaCtrdXZRak5NRQp3bzRlOUNpUW1vWFdoODFONW5Od2R4MFBHUk42bEtJRXcvVXJxeEdISWRLS1VWZzVtRFQ2bFA5NHNhWGpYd3lVCktaREhBeDRJT09sLzY4b203eE1UWmJFNHg2VTRHMm0yVHhidmxET0k4UURwaTh2U2s5ODBSRnUzMU9OeldwWVQKV0Frc0ZYQ0VJaUM3aCs1dFB0SUZ5RnRvUU1JSlo1S3F3RVJRL1NYTWhpazlLaEtPMk1CKy9lQStCcHYvSXI3KwpFTFhMTHhhVUNsc0NBd0VBQWFOZ01GNHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHCkFRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkRYVkFEcmsKbjh2dTdldEhIV3VCaXA3RzI3eE9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUURxR0ErUFE2SERVMDY5VnhSSApjdFlsR1lQaDZ4RHFtRGwvdkFZek40OEsvV3FwMURadTBxWWlhRitscytHYXFvZmlzMlJuRnNjbm12dldqN0IzClgycG5DUG1IVFdwU3ZjQk9qcmgrdFB6RklrVGU5dmFIbzczZDlQZGl4OXFGYjB5akZLMTl2UmZManBaR2ozUjkKM25zZmlGTlpxakVtZDZuK2VoS0tZQjJHK3ZrWWNURmtyUWNIRTRIRGlWYkp2NDhUSHc0MEoreVdvZzEyNlVUcgpLYlFZMk5JaVNqTnd1ay95elNkOWdVZURSU0dRUVJMVlU0Z2R5eDBGZG5QRlZmdGQvRTZhN05KMEJ2YjcvS09aClh4eDR3K3ZPaUVkalZaajdPZXR0aEtGT1pQM2pGTHNIcSt5SnFKVGNDSkNORlFtNmVzZUtBN09VVS90eUtKSDIKUzhJQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBd01RUGpscmpGZUhraElyN1VGUkwzVE9UWVkyRk1GRXR5RjRUVVNBLzFwUzMvQzJFCjVtbGFIZnJtZ3RqeGR5Tzd2Z1R2czkvOGkvU3lBL2UxNXZacDlQV1FTZ0VUT0RNVDh1ZGJ1OE1tc3lWWXhzRFIKdk5zZHZCZlRFNkdLVjRmd1dINlM2OUNNMHdUQ2poNzBLSkNhaGRhSHpVM21jM0IzSFE4WkUzcVVvZ1REOVN1cgpFWWNoMG9wUldEbVlOUHFVLzNpeHBlTmZESlFwa01jREhnZzQ2WC9yeWlidkV4TmxzVGpIcFRnYmFiWlBGdStVCk00anhBT21MeTlLVDN6UkVXN2ZVNDNOYWxoTllDU3dWY0lRaUlMdUg3bTArMGdYSVcyaEF3Z2xua3FyQVJGRDkKSmN5R0tUMHFFbzdZd0g3OTRENEdtLzhpdnY0UXRjc3ZGcFFLV3dJREFRQUJBb0lCQUZZczBBK0J6aGNRUDBxSgpuMFFRQzBJK05scmNHM2k0TWRGclRSTnRhVnlTYTVYTys2VE40RDJhMXNZVUdnNTY2UWxQeDZFUU55U1NKYXJrCmFHdHlLWGdhOTRBOTdzdW0rZm9UTjgwK3R1UkxnOTZHZ0x6Kzc5SVFqSW93STFweUtSNUdwNFBJWGN4UVNuR2kKb09BcGxRclVGeTNPNzRFWC9BZi9vZVExWHBEMjYrUFo5ZU9hS2ZDTkpQeTJqT1BxZkJSZ2VuZzR6c2xkTituMgpaQ3l2NENlREJyR0tIeTR4Ty9tWUwxeXZGRjBhaGw0Njh4dFQvZFAvL0dmUTZUV0JwNmRkVGU3YnNtdVFSbjZICnRkdVdoZzVjSGZwQ3kwQlBNeXZ5dDBJVENMU01XVndCc0xrek1SWXFvakoyVUhoTkhrMVVGME1ncVBBTjQ2N2sKa1BjamV2RUNnWUVBL3lreHNxY0lQc1ZJVVRiWHJRaU5JT051Q0lBeUVxTEdSNnhCUzZ4NFBQcU9GZWtpUnpMVQpYV2RQRXVKRE9FYm15MFk3anpsczlTNE5WN0VaV0Y5bHJBY0FTQk42UjBQaFBSWmhPaE9hUnFDQU9KbzZNWUdkClM0ZzVZU084SmVhWGE1Ymx5UUEzZXhVQ25WUzE1YldTNjEwUTlCeWUzODFVWmk0aFlpME9mejhDZ1lFQXdXWlcKOWRWYnc5V0pRS2JMbEY1QmhSc1RXeTYzWHdYM1VzWlNZN25nUW5oaFFoREJINitYTFlXZ0tSSlBOWjZET0pmNwp2cjE2RkdUNXFmR3Q2ckE5NTRuMDdqUFU3TDNONnN2TmRSV2NHQms2b0JrSnJJOC9GNnFKTFVYajQ2eXlCd2U5CnJxQWZMM09MQlk3cng2bXhDTk8zdCsycVNaMEo2Qko0UWlRZENlVUNnWUJYays0STRhZkUwN1hVbWp4QW1iVEcKMndqRFJpenBsSkQxdkx2VW0yZlJsalg2YzBCZXE2V1VRWWMwZGhDWVdrMlE2NVE1dm40VlVTOG5NQlFBN3cxWQpsRGFXaG9qcnVQS3dJdVJRS0xaRkU0V3U1OUNkZVYxaHRXbnNXM1dTbEtqWU5yeTcxcVUwUzZ2UUVHazJaTEgrCnNyekU3S1hqTHZpTzhicG5sZ3RweFFLQmdGV1VPNWE4dXNhRmp4NlVzREVQSkY4S0JCNnRKV2RlOUhva1dBRFoKRjJ0U2FYY2FndHJLa0ZNTWRqcTJaMmFLcGZZOUNxRDBweml2RmVzbGpwZnpOUEZvRW9IMVhac0V3a0hMdlRhNgpRVUJJcWJCK1k5Ri84YU0vUzBSRlVQcEdTT0RqaEFQcHh1THdkZXdYdWkyMzRTYk95TlVTemUrVkZmVWpkeU9OCloyd2hBb0dBRmVVMHNDNHNscEJUT1VjYXBsMzltS1RkYXRKYjhnNlFtcFAwN2RIV1lWVWpQbWwxcUNHSXNLdWUKTzU5RW9MTllFREZvUGN0VEFmQ1M1VjlSZ29GcXBPSGlHbFNyS1cwZXFQMGJTR3NYTnAvNERqWFMxdERRd3UvSQpQSjdxSWo2Q1BJV1pycFQ1N0NhdmhscFNscEN2M3F1UXVXVDB6azgvK1JQWktsbzdTQXM9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: logging-operator-logging/templates/clusterflows.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: nginx-pods
  namespace: default
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  globalOutputRefs:
  - es
  match:
  - select:
      labels:
        app: nginx-log
      namespaces:
      - default
---
# Source: logging-operator-logging/templates/clusteroutputs.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: es
  namespace: default
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch-es-http.elastic-system.svc.cluster.local
    password:
      valueFrom:
        secretKeyRef:
          key: elastic
          name: elasticsearch-es-elastic-user
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
---
# Source: logging-operator-logging/templates/logging.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-operator-logging
  labels:
    app.kubernetes.io/name: logging-operator-logging
    helm.sh/chart: logging-operator-logging-4.2.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  fluentbit:
    tls:
      enabled: true
      secretName: logging-operator-logging-fluentbit-tls
      sharedKey: ""
  fluentd:
    tls:
      enabled: true
      secretName: logging-operator-logging-fluentd-tls
      sharedKey: ""
    bufferStorageVolume:
      hostPath:
        path: ""
    disablePvc: true
  clusterDomain: cluster.local
  controlNamespace: default


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: sub-argocd
spec:
  destination:
    name: ''
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: fluent/logging-operator-logging
    repoURL: 'git@github.com:BeerLii/EFK.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true