# Default values for logging-operator-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

tls:
  # -- Enable secure connection between fluentd and fluent-bit
  enabled: false

  # -- Specified secret name, which contain tls certs
  fluentdSecretName: ""

  # -- Specified secret name, which contain tls certs
  fluentbitSecretName: ""

  # Shared key between nodes (fluentd-fluentbit)
  sharedKey: ""


# -- Reference to the logging system. Each of the loggingRefs can manage a fluentbit daemonset and a fluentd statefulset.
loggingRef: ""

# -- Disable configuration check before applying new fluentd configuration.
flowConfigCheckDisabled: false

# -- Whether to skip invalid Flow and ClusterFlow resources
skipInvalidResources: false

# -- Override generated config. This is a raw configuration string for troubleshooting purposes.
flowConfigOverride: ""

# -- Flag to disable fluentbit completely
fluentbitDisabled: false
# -- Fluent-bit configurations https://kube-logging.github.io/docs/configuration/crds/v1beta1/fluentbit_types/
fluentbit:
  annotations:
    fluent-setup/enable: "true"
  logLevel: debug
  image:
    pullPolicy: Always
    repository: fluent/fluent-bit
    tag: latest-debug

# -- Flag to disable fluentd completely
fluentdDisabled: false
# -- Fluentd configurations https://kube-logging.github.io/docs/configuration/crds/v1beta1/fluentd_types/
fluentd:
  logLevel: debug
  disablePvc: true
  bufferStorageVolume:
    hostPath:
      path: ""
# 20Gi persistent storage is configured for fluentd by default.
# Here is an example, on how to override it:
#  bufferStorageVolume:
#    pvc:
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 40Gi

# -- Syslog-NG statefulset configuration
syslogNG: {}

# -- Default flow for unmatched logs. This Flow configuration collects all logs that didn’t matched any other Flow.
defaultFlow: {}

# -- GlobalOutput name to flush ERROR events to
errorOutputRef: ""

# -- Global filters to apply on logs before any match or filter mechanism.
globalFilters: []

# -- Limit namespaces to watch Flow and Output custom resources.
watchNamespaces: []

# -- Cluster domain name to be used when templating URLs to services
clusterDomain: "cluster.local"

# -- Namespace for cluster wide configuration resources like ClusterFlow and ClusterOutput. This should be a protected namespace from regular users. Resources like fluentbit and fluentd will run in this namespace as well.
controlNamespace: ""

# -- Allow configuration of cluster resources from any namespace. Mutually exclusive with ControlNamespace restriction of Cluster resources
allowClusterResourcesFromAllNamespaces: false

# -- NodeAgent Configuration
nodeAgents: {}
#  - name: win-agent
#    profile: windows
#    nodeAgentFluentbit:
#      daemonSet:
#        spec:
#          template:
#            spec:
#              containers:
#              - image: banzaicloud/fluentbit:1.9.5
#                name: fluent-bit
#      tls:
#        enabled: false
#  - name: linux-agent
#    profile: linux
#    nodeAgentFluentbit:
#      metrics:
#        prometheusAnnotations: true
#        serviceMonitor: false
#      tls:
#        enabled: false

# -- EnableRecreateWorkloadOnImmutableFieldChange enables the operator to recreate the fluentbit daemonset and the fluentd statefulset (and possibly other resource in the future) in case there is a change in an immutable field that otherwise couldn’t be managed with a simple update.
enableRecreateWorkloadOnImmutableFieldChange: false

# -- ClusterFlows to deploy
clusterFlows:
  - name: nginx-pods
    spec:
      filters:
        - parser:
            remove_key_name_field: true
            reserve_data: true
            parse:
              type: nginx
#      filters:
#        - parser:
#            parse:
#              type: nginx
      match:
        - select:
            namespaces:
              - default
            labels:
              app: nginx-log
      globalOutputRefs:
        - es

# -- ClusterOutputs to deploy
clusterOutputs:
  - name: es
    spec:
      elasticsearch:
        host: elasticsearch-es-http.elastic-system.svc.cluster.local
        port: 9200
        scheme: https
        ssl_verify: false
        ssl_version: TLSv1_2
        user: elastic
        index_name: nginx
        password:
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
        buffer:
          timekey: 1m
          timekey_wait: 30s
          timekey_use_utc: true

# Send all pod logs to kafka
# clusterFlows:
#   - name: all-pods
#     spec:
#       globalOutputRefs:
#         - kafka
# clusterOutputs:
#   - name: kafka
#     spec:
#       kafka:
#         brokers: kafka-headless.kafka.svc.cluster.local:29092
#         format:
#           type: json
#         default_topic: topic

# -- EventTailer config
eventTailer: {}
  # name: sample
  # pvc:
  #   accessModes:
  #     - ReadWriteOnce
  #   volumeMode: Filesystem
  #   storage: 1Gi
  #   storageClassName: standard

# -- HostTailer config
hostTailer: {}
  # name: sample
  # fileTailers:
  #   - name: sample-file
  #     path: /var/log/sample-file
  #     disabled: false
  # systemdTailers:
  #   - name: system-sample
  #     disabled: false
  #     maxEntries: 20
  #     systemdFilter: kubelet.service

# SecurityContextConstraints Roles and RoleBindings for a deployment in OpenShift
scc:
  # -- OpenShift SecurityContextConstraints enabled
  enabled: false
